In [1]:
import numpy as np
import random

## Functions

In [2]:
def create_random_data(number_of_points, number_of_dimentions, distribution):
    created_data = {}
    for dim in range(number_of_dimentions):
        if distribution['name']=='normal':
            generated_values = np.random.normal(distribution['mu'][dim], distribution['sigma'][dim], number_of_points)
        elif distribution['name']=='uniform':
            generated_values = np.array([random.uniform(distribution['min'][dim], distribution['max'][dim]) for _ in range(number_of_points)])
        created_data[dim] = generated_values
    return created_data

In [3]:
def find_number_of_points_with_atleast_one_dim_less_than_val(x, y, val):
    matched_count = 0
    for i in range(x.shape[0]):
        if x[i]<val or y[i]<val:
            matched_count += 1
    print(matched_count)

In [4]:
def find_number_of_points_with_all_dims_less_than_val(x, y, val):
    matched_count = 0
    for i in range(x.shape[0]):
        if x[i]<val and y[i]<val:
            matched_count += 1
    print(matched_count)

In [5]:
def make_array_and_get_basic_information(li):
    arr = np.array(li)
    print(arr.ndim)
    print(arr.dtype)
    print(arr.itemsize)
    return arr

In [6]:
def get_covariance(x, y):
    X = np.stack((x, y), axis=0)
    print(np.cov(X))

In [7]:
def find_max_distance(x, y, ref_point):
    max_dist, max_dist_index = None, None
    for i in range(x.shape[0]):
        d = np.linalg.norm(np.array([x[i], y[i]])-ref_point)
        if max_dist == None or d>max_dist:
            max_dist = d
            max_dist_index = i
    print(max_dist, [x[max_dist_index], y[max_dist_index]])

In [8]:
def calculate_mean_of_points(x, y):
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    mid_point = np.array([x_mean, y_mean])
    print(mid_point)
    return mid_point

In [9]:
def calculate_Euclidean_distance(p1, p2):
    dist = np.linalg.norm(p1-p2)
    print(dist)

## Method 1

In [10]:
data = create_random_data(
    number_of_points = 1000, 
    number_of_dimentions = 2, 
    distribution = {'name':'normal', 'mu':[2, 2], 'sigma': [1, 1]})
x, y = data[0], data[1]
find_number_of_points_with_atleast_one_dim_less_than_val(x, y, val=0)
find_number_of_points_with_all_dims_less_than_val(x, y, val=0)

mean_point = calculate_mean_of_points(x, y)
calculate_Euclidean_distance(mean_point, np.array([2, 2]))

find_max_distance(x, y, np.array([2, 2]))

get_covariance(x, y)

46
0
[2.0011116  1.97592379]
0.024101852894162074
3.603831732064621 [1.2141243123489096, -1.5171014424657714]
[[ 1.0146863  -0.03686357]
 [-0.03686357  1.06603871]]


## Method 2

In [11]:
mean = [2,2]
cov = [[1,0],[0,1]]
x, y, = np.random.multivariate_normal(mean, cov, 1000).T
points = np.stack((x, y), axis=1)
points[:3], x[:3], y[:3]

(array([[3.21299139, 1.38999408],
        [2.78647955, 0.42997765],
        [0.39404957, 3.23513253]]),
 array([3.21299139, 2.78647955, 0.39404957]),
 array([1.38999408, 0.42997765, 3.23513253]))